name: driver
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  bloc: ^8.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.1.17
  conditional_builder_null_safety: ^0.0.6
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  dash_chat_2: ^0.0.6
  dio: ^4.0.4
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.5
  firebase_in_app_messaging: ^0.6.0+6
  firebase_messaging: ^11.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_google_places: ^0.3.0
  flutter_latlong: ^1.0.3
  flutter_local_notifications: ^9.2.0
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_ringtone_player: ^3.2.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.1

  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.7
  google_maps_webservice: ^0.0.19
  html: ^0.15.0
  image_picker_gallery_camera: ^0.2.2
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  location: ^4.3.0
  map_launcher: ^2.1.2
  nations: ^0.0.7
  overlay_support: ^2.0.0
  page_transition: ^2.0.5
  path_provider: ^2.0.8
  pinput: ^2.2.9
  sendbird_sdk: ^3.1.12
  shared_preferences: ^2.0.12
  slide_countdown: ^0.2.5
  sliding_up_panel: ^2.0.0+1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  url_launcher: ^6.0.18
  uuid: ^3.0.6

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/map_style/
    - assets/icons/
    - assets/lang/
